#!/usr/bin/env python
"""One page the operator can work through in minutes: what the harness has filled, and what is
left that only a human can fill.

    /opt/kernel/venv/bin/python tools/deposit_checklist.py
    /opt/kernel/venv/bin/python tools/deposit_checklist.py --primary runs/20260815-target-01

Two tools already know most of this and neither produces a to-do list: `tools/verify_deposit.py`
checks the harness's own work and reports the fields still at their template values (finding 56),
and `tools/fill_registration.py` writes the ~39-item registration form, filling the 32 items that
are facts about the pipeline and marking the 7 that are human attestations (finding 55). This
assembles both into `runs/_deposit/CHECKLIST.md`: every operator blank in one numbered table with
the exact file, the exact key, what to write there and why the harness may not write it, followed
by the exact command sequence for deposit day.

It writes nothing into any `submission_T*/` directory. A deposit is built, never edited
(finding 61), and an attestation is signed by a person, never generated (finding 55).
"""
import argparse, hashlib, json, re, subprocess, sys
from datetime import date
from pathlib import Path

RUN = Path(__file__).resolve().parents[1]
PY = sys.executable

# file -> key -> (what the operator must supply, why the harness may not)
OPERATOR_METADATA = {
    "metadata.json": {
        "team_name": ("the team's real display name",
                      "identity; `check.R` only checks presence, so a placeholder passes green"),
        "contact": ("a corresponding e-mail address",
                    "identity; same false green as team_name"),
        "abstract": ("2-4 sentences describing the entry",
                     "`check.R` does not test this field at all"),
        "code_repository": ("the public repo URL, and `code_doi` once minted",
                            "one of the three standing `make check` warnings"),
        "blinding_attestation": ("an affirmative human signature, or the field left as the "
                                 "operator found it",
                                 "an assertion about HUMAN conduct: it ships pre-set `true` and "
                                 "`check.R` cannot tell an affirmation from the default"),
    },
    ".zenodo.json": {
        "creators": ("real creator names/affiliations/ORCIDs",
                     "authorship; the template's 'Lastname, Firstname' passes presence checks"),
    },
    "registration.md": {
        "(the form itself)": ("copy `registration_draft.md` in, then complete the 7 OPERATOR items",
                              "copying a filled form into the deposit is an operator act"),
    },
}


def run_tool(script, *args):
    p = subprocess.run([PY, str(RUN / "tools" / script), *args], capture_output=True, text=True,
                       cwd=RUN)
    return p.stdout + p.stderr


def operator_items(draft: Path):
    out = []
    for line in draft.read_text().splitlines():
        # only LIST ITEMS: the draft's own preamble explains the OPERATOR marker and is not an item.
        # Before this guard the preamble was rendered as an eighth bullet labelled
        # "(disclosure class)" while the section header said seven - fixed in session 15.
        if line.strip().startswith("- **") and "**OPERATOR**" in line:
            m = re.match(r"- \*\*([^*]+)\*\*", line.strip())
            label = m.group(1).strip() if m else "(disclosure class)"
            body = re.sub(r"\s+", " ", re.sub(r"\*\*", "", line.strip()[2:]))
            out.append((label, body[:400]))
    return out


def main(primary, sensitivity):
    out = RUN / "runs/_deposit"
    out.mkdir(parents=True, exist_ok=True)
    ver = run_tool("verify_deposit.py", primary)
    reg = run_tool("fill_registration.py", primary)
    run_tool("fill_registration.py", sensitivity)
    pending = [l.rstrip() for l in ver.splitlines() if "[PENDING]" in l]
    verdict = next((l.strip() for l in ver.splitlines() if l.startswith("VERDICT")), "")
    items = operator_items(RUN / primary / "registration_draft.md")
    meta = json.loads((RUN / primary / "submission_T1/metadata.json").read_text())
    gates = json.loads((RUN / primary / "gates.json").read_text())

    L = []
    a = L.append
    a("# Deposit checklist - everything the harness can fill, and what only a human can\n")
    a("Generated by `tools/deposit_checklist.py` on %s. Regenerate it after any rebuild; nothing "
      "here is hand-maintained.\n" % date.today().isoformat())
    a("## 1. What is on the table\n")
    cj = RUN / "runs/_deposit/candidates.json"
    cands = json.loads(cj.read_text()) if cj.exists() else None
    if cands:
        a("| | run | card | gates | make check |")
        a("|---|---|---|---|---|")
        for c in cands["candidates"]:
            gp = RUN / c["run"] / "gates.json"
            g = json.loads(gp.read_text()) if gp.exists() else {}
            ok = all(v.get("passed") if isinstance(v, dict) else v for v in g.values()) and g
            mark = "**RECOMMENDED**" if c["run"] == cands.get("recommended_primary") else c["id"]
            a("| %s | `%s` | %s | %s | %s |"
              % (mark, c["run"], c["card"], "all green" if ok else "SEE gates.json",
                 "PASS (3/3)" if (RUN / c["run"] / "submission_T3").exists() else "-"))
        a("")
        a("**Recommended primary: `%s`.** %s\n"
          % (cands["recommended_primary"], cands["recommendation_grounds"]))
        a("What each choice risks and buys:\n")
        for c in cands["candidates"]:
            a("* **%s** (`%s`) - %s" % (c["id"], c["run"], c["role"]))
            a("  * buys: %s" % c["buys"])
            a("  * risks: %s" % c["risk"])
            if c["changes"]:
                a("  * changes vs target-01: %s" % "; ".join(c["changes"]))
        a("")
        a("All four submit the **same 208 predicted effects** except `target-02-pooled`. No "
          "prediction was made or changed in producing any of them: target-03 and target-04 cost "
          "**0 model tokens** and their `card/ate.csv` is byte-identical to target-01's "
          "(`b382cd499264a6f9`). **Naming the entry is the operator's call.**\n")
    else:
        a("| | run | card | status |")
        a("|---|---|---|---|")
        a("| **primary candidate** | `%s` | unshrunk (lambda NOT applied) | %s |"
          % (primary, "all gates green" if all(gates.values()) else "GATES: %s" % gates))
        a("| sensitivity | `%s` | pooled lambda = 1.5212 applied | retained, complete, gate-green |"
          % sensitivity)
        a("")
    a("`team_id` is `team_31`; every prediction file is stamped `team_31_`. Deposit window: "
      "**2026-08-28 .. 2026-08-31**, and `--strict` refuses to call a deposit ready outside it.\n")

    a("## 2. What the harness has already filled\n")
    a("* **%d of ~39 registration items** are filled from artefacts, each citing its source file: "
      "`%s/registration_draft.md` (regenerated just now, so its spend and model numbers are "
      "current)." % (len([l for l in reg.splitlines() if "filled from artefacts" in l]) and
                     int(re.search(r"filled from artefacts: (\d+)", reg).group(1)), primary))
    a("* `approach_family` = `%s`" % meta.get("approach_family", "?"))
    a("* `models` = `%s`" % meta.get("models", "?"))
    a("* `publication_status` = `%s`" % meta.get("publication_status", "?"))
    a("* Deposit self-verification: `%s`" % verdict)
    a("* The raw model logs are staged and replayable (`%s/raw_model_logs/`, "
      "`MANIFEST.sha256` verifies under plain `sha256sum -c`), which is what registration K.2 "
      "requires; whether they go in-repo or to a linked Zenodo record is an operator choice.\n"
      % primary)

    # --- operator rulings and the no-change ledger, both DATA (runs/_deposit/*.json) ------------
    rul = json.loads((out / "rulings.json").read_text()) if (out / "rulings.json").exists() else None
    if rul:
        a("## 2b. Operator rulings already on the record\n")
        a("| # | recorded | subject | ruling | still to review |")
        a("|---|---|---|---|---|")
        for i, r in enumerate(rul["rulings"], 1):
            a("| %d | %s (session %s) | %s | **%s** | %s |"
              % (i, r["date_recorded"], r["session"], r["subject"], r["ruling"], r["review"]))
        a("")
        for r in rul["rulings"]:
            a("* **%s** grounds: %s  \n  evidence: `%s`" % (r["id"], r["grounds"], r["evidence"]))
        a("")

    led = json.loads((out / "ledger.json").read_text()) if (out / "ledger.json").exists() else None
    if led:
        a("## 2c. Why no PREDICTION has changed since the card was built\n")
        a("Every campaign experiment since `%s` was pre-registered before it was run, and every one "
          "came back null or below the target study's own resolution. The card the operator is "
          "naming is therefore the same card the campaign started with, and that is a result "
          "rather than an omission.\n" % primary)
        a("| session | question | verdict | rerun with |")
        a("|---|---|---|---|")
        for e in led["entries"]:
            a("| %s | %s | %s | `%s` |" % (e["session"], e["question"], e["verdict"], e["tool"]))
        a("")
        h = {}
        for f in sorted((RUN / primary / "card").glob("*.csv")):
            h[f.name] = hashlib.sha256(f.read_bytes()).hexdigest()[:16]
        a("Card files as deposited (sha256, first 16): %s\n"
          % ", ".join("`%s` %s" % (k, v) for k, v in h.items()))

    a("## 3. Operator blanks - the whole list\n")
    a("| # | file | key | what to write | why the harness must not |")
    a("|---|---|---|---|---|")
    n = 0
    for f, keys in OPERATOR_METADATA.items():
        for k, (what, why) in keys.items():
            n += 1
            a("| %d | `submission_T{1,2,3}/%s` | `%s` | %s | %s |" % (n, f, k, what, why))
    a("")
    a("Same list as `verify_deposit.py` reports, verbatim:\n")
    a("```")
    for p in pending:
        a(p)
    a("```\n")
    a("### The %d registration items that need a human\n" % len(items))
    for label, body in items:
        a("* **%s** - %s" % (label, body))
    a("")

    a("## 3b. Two decisions that are not blanks in a file\n")
    a("**(i) The exposure / disclosure declaration.** `disclosure_class` is still unset and it is "
      "the one operator field with no template default to inherit, so nothing will warn about it. "
      "Every input this pipeline used is either public or in this repo, no material is withheld, "
      "and nothing requires escrow, so **class A (Open) is achievable** - but the choice is the "
      "operator's and it must be typed into `metadata.json` -> `disclosure_class` in all three "
      "tiers. Declare alongside it any exposure the harness cannot see: prior sight of the target "
      "study's materials by a human team member, contact with the organisers, and any funding or "
      "model-access relationship (registration I.1). The harness's own exposure is recorded and "
      "is nil: the stage-5a blinding probe ran **before any prediction call** and returned CLEAN, "
      "and a `RESULTS_KNOWN: YES` would have aborted the batch (red path asserted in "
      "`tools/test_gates.py`).\n")
    a("**(ii) K.2 - where the raw model logs go.** K.2 requires the complete unprocessed model "
      "responses to be **deposited**, hashed and time-stamped, and explicitly allows either an "
      "in-repo copy or a separate linked Zenodo record. They are staged and replayable at "
      "`runs/20260815-target-01/raw_model_logs/` - 4 prompts, 4 unprocessed completions, 4 "
      "provider envelopes, and a `MANIFEST.sha256` that verifies under plain `sha256sum -c` "
      "(re-verified this session: all OK). **One bundle covers four of the five candidates**, "
      "because `target-01`, `target-01b`, `target-03` and `target-04` all submit the same 208 "
      "effects from the same four completions (`card/ate.csv` sha256 `b382cd499264a6f9` on all "
      "four); `target-02-pooled` is those same completions times the fitted 1.5212. So deposit "
      "the bundle **once** and cite it from each entry. Do **not** put it in "
      "`raw_data_deposit/`: that directory is the Qualtrics-export path for pipelines that "
      "simulate a survey export, and an analysis-first pipeline correctly leaves it empty.\n")

    a("## 4. Deposit-day sequence\n")
    a("```bash")
    a("PY=/opt/kernel/venv/bin/python")
    a("# 0. CHOOSE THE ENTRY. The recommendation is in section 1; RUN=<the chosen run>.")
    a("#    If more than one is deposited at a tier, rebuild the extras with --entry secondary-1")
    a("#    etc. so the filename check passes (only primary|secondary-k survives make check).")
    a("RUN=%s" % (cands.get("recommended_primary") if cands else primary))
    a("# 1. rebuild the deposit so its build stamp falls inside the window (never edit a")
    a("#    submission directory by hand - finding 61)")
    a("$PY tools/restamp_deposit.py $RUN")
    a("# 2. fill the six metadata/zenodo blanks above in all three tiers, then re-run make check")
    a("for t in 1 2 3; do (cd $RUN/submission_T$t && make check); done")
    a("# 3. copy registration_draft.md into each tier's registration.md, complete the 7 items")
    a("#    and type disclosure_class (section 3b(i))")
    a("# 4. gate the deposit on the operator items and the window")
    a("$PY tools/verify_deposit.py $RUN --strict")
    a("# 5. only then upload; the Zenodo lock is an operator act and the prediction lock is")
    a("#    2026-08-31")
    a("```\n")
    a("## 5. What must NOT happen\n")
    a("* No prediction changes. The card was built blind, before any of this, and editing a "
      "number now would be choosing an output from a diagnostic.")
    a("* No hand edits inside `submission_T*/`: rebuild instead, so `make check` and the gate "
      "record refer to the bytes that exist.")
    a("* No harness-written attestation. `blinding_attestation` and registration I.3 are claims "
      "about human conduct; the pipeline's evidence for them is cited in the draft, and the "
      "signature is not the harness's to give.")

    (out / "CHECKLIST.md").write_text("\n".join(L) + "\n")
    print("wrote runs/_deposit/CHECKLIST.md  (%d operator blanks, %d registration items needing a "
          "human)" % (n, len(items)))
    print(verdict)


if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--primary", default="runs/20260815-target-01")
    ap.add_argument("--sensitivity", default="runs/20260815-target-02-pooled")
    x = ap.parse_args()
    main(x.primary, x.sensitivity)
