#!/usr/bin/env python
"""Fill the deposit's registration form from the run's own artefacts. Finding 26, extended.

`check.R` emits a standing warning about `registration.md`'s items and the harness had filed all of
them as operator-owned. Finding 26 is what makes that suspicious: `approach_family` and `models` were
filed the same way, were facts only the harness knew, and would have shipped as the template's false
defaults. Read every field a template hands you and ask whether it is true - and whether you are the
one who knows it.

    /opt/kernel/venv/bin/python tools/fill_registration.py runs/20260815-target-01

Writes `runs/<id>/registration_draft.md`. It does NOT touch the deposit: the verified
`submission_T*/registration.md` is left exactly as `make check` saw it, and copying the draft in is
an operator act like every other part of the deposit.

Two rules it holds to, and the second is the one that matters:
  - every filled item cites the artefact it came from, so a claim in the form can be traced to a file;
  - anything the harness does not know is written `OPERATOR - <what is needed>` and never guessed.
    A registration form is an attestation. A plausible value invented here is worse than a blank.
"""
import argparse, json, sys
from pathlib import Path

import pandas as pd

RUN = Path(__file__).resolve().parents[1]
OP = "**OPERATOR** - "


def load(p, default=None):
    try:
        return json.loads(Path(p).read_text())
    except Exception:
        return default if default is not None else {}


def main(run):
    d = RUN / run
    if not d.exists():
        raise SystemExit(f"no such run: {d}")
    rj = load(d / "run.json")
    sm = load(d / "stages/summary.json")
    cost = load(d / "stages/target/cost.json")
    spend = load(d / "stages/target/spend.json")
    lam = load(d / "stages/calibration/lambda.json")
    meta = load(d / "card/meta.json")
    probe = load(d / "stages/target/blinding_probe.json")
    md = load(d / "submission_T1/metadata.json")
    t1 = pd.read_csv(d / "stages/tier1.csv")
    ate = pd.read_csv(d / "card/ate.csv")
    model = cost.get("model") or meta.get("model", "?")
    draws = cost.get("draws", "?")
    binr = sm.get("binary", {})
    per = t1[t1.condition != "control"].condition.value_counts()

    E = lambda s: f"  \n  *(source: {s})*"          # noqa: E731
    L = []
    A = L.append
    A(f"# Method registration form - DRAFT filled from `{run}`\n")
    A("Generated by `tools/fill_registration.py` from this run's recorded artefacts. Every filled "
      "item cites its source file. Items the harness cannot know are marked "
      "**OPERATOR** and are left for a human; nothing here is guessed.\n")
    A(f"Run `{rj.get('run_id')}`, started {rj.get('started')}, frozen-file sha256 "
      f"`{str(rj.get('frozen_sha256'))[:16]}`, inputs sha256 "
      f"`{str(rj.get('params', {}).get('inputs_sha256'))[:16]}`.\n\n---\n")

    A("## 0 - Approach identity and output")
    A(f"- **0.1 Team** - {OP}name, affiliations, corresponding contact. "
      f"`metadata.json` records team_id `{md.get('team_id')}`.")
    A(f"- **0.2 Plain-language summary** - {OP}one paragraph for a public audience. The harness's "
      "own description: this approach predicts the study's published analysis results directly - "
      "treatment effects, condition means, subgroup levels and response distributions - and then "
      "generates an individual-level dataset backwards from those predictions, so that re-running "
      "the benchmark's analyses on it reproduces them. It never simulates a respondent answering "
      "a question. Operator to approve or rewrite.")
    A(f"- **0.3 Submission tier & approach family** - tier {md.get('tier')}; "
      f"{md.get('approach_family')}" + E("submission_T*/metadata.json, written by the harness "
                                         "because the template default was false - finding 26"))
    A("- **0.4 Pipeline diagram** - stages 0-9 of `AGENTS.md`: open -> inputs -> carve -> practice "
      "(model) -> calibrate -> **predict the target (model)** -> card -> synthesise -> deposit -> "
      "close. Exactly two stages call a model; all others are deterministic code."
      + E("AGENTS.md stage table; runs/<id>/stages/"))
    A(f"- **0.5 Coverage** - **{len(ate)} predicted cells = 16 interventions x 13 outcomes**, "
      f"all 17 conditions present, every cell exactly once, no NA. Tier-1 file carries "
      f"**{len(t1):,} respondents** ({per.min():,} per intervention, "
      f"{(t1.condition == 'control').sum():,} control)."
      + E("tools/verify_deposit.py, which recomputes this from the deposited rows"))

    A("\n## A - Scope of LLM use")
    A(f"- **A.1 Purpose** - an LLM is called at exactly two workflow stages: practice prediction on "
      f"held-out training tasks (stage 3) and the target prediction itself (stage 5), plus a "
      f"recognition/blinding probe before each. Card assembly, calibration, backward synthesis, "
      f"deposit and gates are deterministic code with no model call."
      + E("stages/target/cost.json: %s calls this stage" % cost.get("calls")))
    A("- **A.2 Degree of automation** - fully automated; no human in the loop at prediction time. "
      "No human edited any prediction; the pipeline is a script (`tools/target.py`) whose model "
      "calls are cached on a key covering the prompt and every sampling parameter."
      + E("frozen definitions require this; runs/<id>/stages/target/ holds every transcript"))

    A("\n## B - Model / system details")
    A(f"- **B.1 Model name(s)** - `{model}` via the Claude CLI, resolved binary "
      f"`{binr.get('resolved')}` sha256 `{binr.get('sha256')}`." + E("stages/summary.json"))
    A(f"- **B.2 Access & context mode** - command-line `claude -p`, **stateless** "
      f"(`--no-session-persistence`), one user message per call, no chat history. "
      f"Call date {str(rj.get('started'))[:10]}." + E("ssb.predict.command(), frozen definitions"))
    A(f"- **B.3 Configuration** - provider default sampling, never tuned per task; "
      f"`MAX_THINKING_TOKENS=0`; no temperature/top-p/penalty/stop overrides; "
      f"**{draws} completions per item**." + E("frozen definitions; stages/target/cost.json"))
    A("- **B.4 Customization** - **none.** No fine-tuning, no RAG, no retrieval, no web search, no "
      "tool use (`--tools \"\"`), no agentic scaffold. The frozen definitions require a plain "
      "completion and forbid an agent runtime for any prediction." + E("frozen definitions"))
    A("- **B.5 Persistent memory** - none across interactions (`--no-session-persistence`, and "
      "ancestor instruction files excluded via `claudeMdExcludes`)." + E("ssb.predict.command()"))
    A("- **B.6 Inference stack** - N/A, hosted model, not served locally.")
    A(f"- **B.7 Ensembles** - {draws} independent completions of the identical prompt from one "
      f"model, aggregated **cell-wise by median**. Measured value of the extra draws on practice: "
      f"-0.0002 directional / +0.0041 rho / -0.0014 pp RMSE."
      + E("tools/draws_value.py; AGENTS.md finding 43"))

    A("\n## C - Prompts")
    A("- **C.1 Exact prompts** - verbatim, deposited: `stages/target/system.txt` and "
      "`stages/target/user.txt` (and `probe_user.txt` for the blinding probe). **Pre-specified**: "
      "assembled by `ssb.predict` from frozen inputs, and the inputs tree is hash-pinned, so the "
      "prompt could not be tuned in response to target outputs." + E("run.json params.inputs_sha256"))
    A("- **C.2 System-wide instructions** - `stages/target/system.txt`, deposited verbatim.")
    A("- **C.3 Prompt-design rationale** - prompts present the message texts, item wordings, sample "
      "description and arm sizes, and ask for an arm x outcome effect table in percentage points. "
      "Practice and target prompts share one shape and one size band (24,000-token budget, "
      "12,000-char per-arm cap) so a practice score and a target score mean the same thing."
      + E("AGENTS.md finding 17; RUNBOOK.md section 3"))

    A("\n## D - Persona / profile construction")
    A("- **D.1 Profile source** - public survey microdata (ACS/CES) used to build a joint "
      "demographic pool; condition assignment is by the harness. **No profile was ever shown to a "
      "model**: this approach is analysis-first, so profiles exist only to carry the backward "
      "synthesis." + E("tools/build_pool.py -> inputs/pool/joint.csv"))
    A("- **D.2 Profile verbalization** - **N/A.** No persona was verbalized or sent to any model; "
      "no per-respondent generation occurs anywhere in the pipeline.")
    A(f"- **D.3 Assignment & weighting** - {len(t1):,} synthetic respondents over all 17 "
      f"conditions, {per.min():,} per intervention and "
      f"{(t1.condition == 'control').sum():,} in control, drawn from the joint pool; no reuse "
      f"across conditions." + E("stages/tier1.csv"))

    A("\n## E - Stimulus and survey administration")
    A("- **E.1 Stimulus presentation** - **verbatim**, never paraphrased or summarised. The target "
      "brief is never truncated and never split: `tools/target.py` aborts if either happens, and "
      "the longest target arm is 11,134 chars against a 12,000 cap." + E("AGENTS.md finding 44"))
    A("- **E.2 Survey walk-through** - **N/A.** No survey is administered to a model; predictions "
      "are made at the analysis level in one call per draw, not item by item.")
    A("- **E.3 Response elicitation** - constrained structured output: a CSV of condition, outcome "
      "and effect in percentage points, parsed by `ssb.predict.parse`. An unparsed cell **aborts "
      "the run** rather than being deposited as a null." + E("tools/test_parse.py, 13 recovery "
                                                             "modes and 7 negative controls"))

    A("\n## F - Stochasticity and aggregation")
    A(f"- **F.1 Runs & seeds** - {draws} independent completions per prompt at provider-default "
      f"sampling; no seed is exposed by the API, so runs are not bit-reproducible, but every "
      f"completion is cached under a key covering the prompt and all sampling parameters and the "
      f"raw transcripts are deposited. Backward synthesis is seeded and its gate is scanned over "
      f"5 seeds." + E("stages/summary.json seed_scan"))
    A("- **F.2 Aggregation rule** - cell-wise **median** across draws.")

    A("\n## G - Validation & post-processing")
    A("- **G.1 Human validation** - **none.** No human reviewed, edited or selected any prediction.")
    A(f"- **G.2 Post-processing** - parser tolerates delimiter/format variation but an unparsed "
      f"cell aborts; no exclusions, no refusals encountered; percentage points converted to each "
      f"outcome's native units with a clipping report that aborts if non-empty. Effective N per "
      f"condition: {per.min():,} per intervention, {(t1.condition == 'control').sum():,} control."
      + E("AGENTS.md findings 8 and 24"))
    pol = lam.get("_policy") or meta.get("lambda_policy")
    # A missing artefact must be REPORTED, not crashed on: a run that inherits its calibration
    # from another run carries no lambda.json of its own, and formatting None raised TypeError.
    _lp = lam.get("_pooled")
    _lam_txt = f"{_lp:.4f}" if isinstance(_lp, (int, float)) else "OPERATOR - lambda.json absent"
    _n_txt = lam.get("_n", "OPERATOR - unknown")
    A(f"- **G.3 Calibration corrections** - policy **`{pol}`**. A magnitude multiplier was fitted "
      f"on practice pairs (**lambda = {_lam_txt}** on {_n_txt} in-slope "
      f"(predicted, human) pairs from held-out training tasks) and, under this policy, "
      f"**{'was NOT applied - the deposited effects are unshrunk' if str(pol) == 'none' else 'was applied to all cells'}**. "
      f"Fitted only on training-task data; no target data was used." + E("stages/calibration/lambda.json"))

    A("\n## H - Learning and conditioning components")
    A("- **H.1 Fine-tuning data** - **N/A.** No fine-tuning.")
    A("- **H.2 Context & retrieval corpora** - **N/A.** No retrieval and no indexed corpus. The "
      "only text in context is the prompt deposited under C.1.")

    A("\n## I - Data inputs, blinding, and competing interests")
    A(f"- **I.1 Competing interests** - {OP}funding, in-kind compute or model access, and any "
      f"relationship with LLM-interested entities. The harness cannot know these.")
    A("- **I.2 External human data** - the five public training studies carved into practice tasks, "
      "plus published survey sources used to anchor control levels and subgroup offsets (Pew ATP "
      "waves, GSS, TISP, CCAM and the ACS/CES pool). Every anchor is recorded with its cut and "
      "source." + E("inputs/baselines/provenance.json; notes/DATA_*.md"))
    A(f"- **I.3 Blinding attestation** - {OP}**a signed human attestation, which a harness cannot "
      f"provide.** The evidence supporting it: the pipeline ran a blinding probe against the model "
      f"**before any prediction call**, asking whether it already knew this study's results; the "
      f"verdict was **{probe.get('verdict')}** (self-report "
      f"`{probe.get('self_report_results_known')}`; the probe's `CONFIDENCE` field has no defined "
      f"referent and is deliberately NOT quoted here - OPEN 36), and a `YES` would have aborted "
      f"the run before a "
      f"single prediction was made. Practice ground truth is held out structurally: the predictor "
      f"is a plain completion with no filesystem, and every transcript is leak-audited against the "
      f"sealed values with a positive control." + E("stages/target/blinding_probe.json; "
                                                    "AGENTS.md findings 35 and 38"))
    A(f"- **I.4 Contamination note** - {OP}model training cutoff versus the public release dates of "
      f"this project's materials. Harness-side evidence: the recognition probe was run against all "
      f"five *training* studies, which are published papers, and recognised two of five by name; "
      f"the identical probe pointed at the target returned "
      f"`{probe.get('self_report_results_known')}`." + E("stages/practice/recognition_probe.json"))

    A("\n## J - Internal selection procedure")
    other = sorted(p for p in (RUN / "runs").glob("*/stages/practice/spend.json")
                   if p.parent.parent.parent.name != str(meta.get("practice_run")))
    # NEWLY paid tokens only. `prior_billed_tokens` is cache reuse - money already spent, and
    # already counted in whichever run first paid it. Adding it here double-counts: the session-7
    # length experiment's `base` arm is a pure cache replay of the PIPELINE's own practice calls,
    # so summing the batch totals charged the deposit 253,364 tokens twice. A registration form is
    # an attestation (finding 55); a figure in it that counts the same money twice is wrong even
    # though every input to it was right.
    extra = sum(load(p).get("billed_tokens", 0) for p in other)
    reused = sum(load(p).get("prior_billed_tokens", 0) for p in other)
    A("- **J.1 Design-space search** - the pipeline was developed over recorded runs in "
      "`runs/scoreboard.csv`, one row per (run, task), every metric recomputable from the run's own "
      "stored (predicted, human) pairs. Internal validation criterion: beat both scripted baselines "
      "on the same task, with cluster-bootstrap intervals on the margin. Calibration variants, the "
      "number of draws and the panel design were all chosen leave-one-task-out on practice data "
      "only. **No target data entered any selection decision** - none exists."
      + E("tools/verify_scoreboard.py, tools/calibration_variants.py, tools/margin_ci.py"))
    if extra:
        A(f"  Additional model spend on experiments that are NOT part of the submitted "
          f"pipeline: **{extra:,} newly-billed tokens** across {len(other)} run(s) "
          f"(a further {reused:,} tokens in those runs were cache replays of calls already paid "
          f"for and counted inside the pipeline total, and are deliberately not added again). "
          f"Two experiments: a single practice draw from a second model, to test whether a "
          f"two-model panel decorrelates the errors - it does not (prediction correlation +0.889), "
          f"so the deposited entry uses one model; and a pre-registered length-controlled prompt "
          f"experiment over five prompt variants, which returned a null - no prompt change removed "
          f"the predictor's message-length over-weighting without costing accuracy, so no prompt "
          f"used in the deposit was altered by it."
          + E("tools/models_value.py; " + ", ".join(p.parent.parent.parent.name for p in other)))

    A("\n## K - Reproducibility & frozen artifacts")
    A(f"- **K.1 Code & materials** - {OP}public repository link/DOI, then record it in "
      f"`metadata.json` -> `code_repository` / `code_doi` (currently the template placeholder, and "
      f"one of the three standing `make check` warnings).")
    A(f"- **K.2 Raw output logs** - complete unprocessed model responses archived in the run: "
      f"`stages/target/transcript_draw*.txt` and `probe_completion.txt`, plus the cached JSON "
      f"envelopes under `runs/_cache/completions/`. Prompts, transcripts and the resolved binary's "
      f"sha256 are all recorded." + E("stages/target/"))
    pr_run = meta.get("practice_run")
    psp = load(RUN / "runs" / str(pr_run) / "stages/practice/spend.json")
    pco = load(RUN / "runs" / str(pr_run) / "stages/practice/cost.json")
    p_new = psp.get("billed_tokens", 0)
    p_prior = psp.get("prior_billed_tokens", 0)
    A(f"- **K.3 Computational resources** - target stage: **{cost.get('calls')} model calls** "
      f"({draws} prediction draws + 1 blinding probe), "
      f"**{spend.get('billed_tokens', 0):,} billed tokens**, "
      f"${spend.get('billed_usd', 0):.2f}, wall clock {sm.get('seconds', 0):.0f} s including "
      f"backward synthesis and three validator runs. Practice stage (`{pr_run}`): "
      f"**{pco.get('calls', '?')} calls, {p_new + p_prior:,} billed tokens** for the batch, of "
      f"which {p_new:,} was newly paid and {p_prior:,} was already-paid cache reuse from an "
      f"interrupted earlier attempt at the identical prompts. "
      f"**Total across both stages: {spend.get('billed_tokens', 0) + p_new + p_prior:,} billed "
      f"tokens.** Tokens are the provider's own billed counts, not a tokenizer proxy - the two "
      f"differ by 2.44x here."
      + E("stages/target/spend.json and %s/stages/practice/spend.json; AGENTS.md finding 28"
          % pr_run))

    A("\n## L - Disclosure class")
    A(f"- {OP}choose **A / B / C** and record it in `metadata.json` -> `disclosure_class`. Every "
      f"item above is either public in this repo or marked OPERATOR; the harness holds nothing "
      f"back, so **class A (Open) is achievable** once the OPERATOR items are completed. Nothing "
      f"in this pipeline requires escrow.")

    A("\n---\n")
    n_op = sum(1 for x in L if OP in x)
    A(f"*{len(ate)} cells, {len(t1):,} rows. Items filled from artefacts: "
      f"{sum(1 for x in L if x.startswith('- **') and OP not in x)}. "
      f"Items left for the operator: {n_op}.*")

    out = d / "registration_draft.md"
    out.write_text("\n".join(L) + "\n")
    print(f"wrote {out}")
    print(f"  filled from artefacts: {sum(1 for x in L if x.startswith('- **') and OP not in x)} items")
    print(f"  left for the operator: {n_op} items")
    print("  the deposit's own registration.md is UNTOUCHED - copying this in is an operator act")
    return 0


if __name__ == "__main__":
    a = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    a.add_argument("run", nargs="?", default="runs/20260815-target-01")
    sys.exit(main(a.parse_args().run))
